version: '3'

services:
  mysql-db:
    container_name: smk-db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: smarkio-teste
      MYSQL_ROOT_PASSWORD: 123456
      TZ: America/Sao_Paulo
    volumes: 
      - ./src/database/docker-volume:/etc/mysql/conf.d
    ports:
      - 3306:3306
    networks:
      - smk-teste
  node-api:
    container_name: smk-api
    env_file:
      - .env
    build: 
      context: .
    depends_on:
      - mysql-db
    volumes: 
      - "${PWD}:/app"
    ports: 
      - 3333:3333
    networks:
      - smk-teste

networks: 
  smk-teste: