version: '3'

services:
  mysql-db:
    container_name: smk-db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: smarkio-teste
      MYSQL_ROOT_PASSWORD: 123456
      TZ: America/Sao_Paulo
    volumes: 
      - ./src/database/docker-volumes:/etc/mysql/conf.d
    ports:
      - 3306:3306
    networks:
      - smk-teste
  node-api:
    container_name: smk-api
    image: node:14.17
    depends_on:
      - mysql-db
    volumes: 
      - ./:/smk-api
    ports: 
      - 3333:3333
    command: bash -c "cd /smk-api && npm i && npm run dev"
    networks:
      - smk-teste

networks: 
  smk-teste: